### ISSUE TITLE
yo web-extension throws Unexpected Identifier error

### ISSUE THREAD

**Issue by smileavi** [HaNdTriX/generator-web-extension#5]
After installing, yo and web-extension generator,  when i run **yo web-extension**
the error is displayed.

`/usr/local/lib/node_modules/generator-web-extension/app/index.js:26
  async prompting () {
        ^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as web-extension:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:38:27)
`
node --version
v6.11.2

**Comment by sookinoby** [comment]
Can you try upgrading to node v8.9.4?
I had the same issue, I fixed to making a clone of repo and modifying the index.js to use no asyn prompting.
But if you upgrade to v8.9.4, you will be fine.
